# Generated by Django 3.2.18 on 2024-01-15 07:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0002_alter_blog_managers_remove_blog_menu_blog_tags_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='favourites',
            field=models.ManyToManyField(blank=True, default=None, related_name='favourite', to=settings.AUTH_USER_MODEL),
        ),
    ]
