# Generated by Django 4.0.4 on 2022-04-29 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_blog_menu'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='menu',
        ),
        migrations.DeleteModel(
            name='Menu',
        ),
    ]
