# Generated by Django 4.0.4 on 2022-04-29 06:41

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_remove_blog_menu_delete_menu'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='blog',
            managers=[
                ('published', django.db.models.manager.Manager()),
            ],
        ),
    ]
